kind: Deployment
apiVersion: apps/v1
metadata:
  name: wapmh-app
  labels:
    app: wapmh
spec:
  selector:
    matchLabels:
      app: wapmh
  template:
    metadata:
      labels:
        app: wapmh
    spec:
      containers:
        - name: wapmh-app
          image: 'ghcr.io/deutsche-nationalbibliothek/wapmh:main'
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: wapmh-configmap
          volumeMounts:
            - mountPath: {{ .Values.queryDirectory | quote }}
              name: wapmh-query-collection
      volumes:
        - name: wapmh-query-collection
          configMap:
            name: wapmh-query-collection-configmap
            items:
              - key: "allHeadersSelect.rq"
                path: "allHeadersSelect.rq"
              - key: "dateRangeHeadersSelect.rq"
                path: "dateRangeHeadersSelect.rq"
              - key: "allHeadersSelect.rq"
                path: "identifiedHeaderSelect.rq"
              - key: "recordConstruct.rq"
                path: "recordConstruct.rq"
              - key: "recordOaiDcConstruct.rq"
                path: "recordOaiDcConstruct.rq"
