kind: Deployment
apiVersion: apps/v1
metadata:
  name: pwidresolver-app
  labels:
    app: pwidresolver
spec:
  selector:
    matchLabels:
      app: pwidresolver
  template:
    metadata:
      labels:
        app: pwidresolver
    spec:
      containers:
        - name: pwidresolver-app
          image: 'ghcr.io/deutsche-nationalbibliothek/pwidresolver:main'
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.pwidResolverBasePath | quote }}
            - name: LOGGING_LEVEL_ROOT
              value: {{ .Values.pwidResolverLoglevel | quote }}

