kind: Service
apiVersion: v1
metadata:
  name: pwidresolver-service
spec:
  selector:
    app: pwidresolver
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pwidresolver-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /pwidresolver
            pathType: Prefix
            backend:
              service:
                name: pwidresolver-service
                port:
                  number: 8080
---
{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pwidresolver-default-route
spec:
  to:
    kind: Service
    name: pwidresolver-service
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pwidresolver-apps-route
spec:
  host: {{ .Values.routerHost | quote }}
  path: /pwidresolver
  to:
    kind: Service
    name: pwidresolver-service
  port:
    targetPort: 8080
{{- end }}